# This workflow will generate a distribution and upload it to PyPI

name: Publish Alpha Build ...aX
on:
  push:
    branches:
      - dev
    paths-ignore:
      - 'test/**'
      - 'examples/**'
      - '.github/**'
      - '.gitignore'
      - 'LICENSE'
      - 'CHANGELOG.md'
      - 'MANIFEST.in'
      - 'readme.md'
      - 'scripts/**'
      - 'translations/**'
  workflow_dispatch:

jobs:
  publish_alpha_release:
    uses: neongeckocom/.github/.github/workflows/publish_alpha_release.yml@master
    secrets:
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
    with:
      version_file: "version.py"
      publish_prerelease: true
      update_changelog: true